[package]
name = "kitsune-search-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.6"
tonic = { version = "0.8.3", default-features = false, features = ["codegen", "transport", "prost"] }

[build-dependencies]
tonic-build = "0.8.4"
