[package]
name = "kitsune-embed"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
diesel = "2.1.4"
diesel-async = "0.4.1"
embed-sdk = { git = "https://github.com/Lantern-chat/embed-service.git", rev = "b00278f1d2c41bc4394d394426dff0ecf8e42c90" }
http = "1.0.0"
iso8601-timestamp = "0.2.16"
kitsune-db = { path = "../kitsune-db" }
kitsune-http-client = { path = "../kitsune-http-client" }
once_cell = "1.19.0"
scraper = { version = "0.18.1", default-features = false }
smol_str = "0.2.0"
thiserror = "1.0.56"
typed-builder = "0.18.0"

[lints]
workspace = true
