[package]
name = "kitsune-captcha"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bytes = "1.5.0"
enum_dispatch = "0.3.12"
http = "1.0.0"
http-body-util = "0.1.0"
kitsune-http-client = { path = "../kitsune-http-client" }
serde = { version = "1.0.195", features = ["derive"] }
serde_urlencoded = "0.7.1"
simd-json = "0.13.6"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.56"
typed-builder = "0.18.0"

[lints]
workspace = true
