[package]
name = "kitsune-captcha"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
enum_dispatch = "0.3.12"
http = "0.2.11"
kitsune-http-client = { path = "../kitsune-http-client" }
serde = { version = "1.0.193", features = ["derive"] }
serde_urlencoded = "0.7.1"
simd-json = "0.13.4"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
typed-builder = "0.18.0"

[lints]
workspace = true
