[package]
name = "kitsune-email"
authors.workspace = true
edition.workspace = true
version.workspace = true

[package.metadata.cargo-machete]
ignored = ["askama_axum"] # See reason below.

[dependencies]
askama = "0.12.1"
askama_axum = "0.3.0" # Damn it, cargo. Because "kitsune" uses "askama" with the axum feature, we have to have the crate available here as well..
diesel = "2.1.4"
diesel-async = "0.4.1"
kitsune-db = { path = "../kitsune-db" }
kitsune-url = { path = "../kitsune-url" }
lettre = { version = "0.11.2", default-features = false, features = [
    "builder",
    "hostname",
    "pool",
    "smtp-transport",
    "tokio1",
    "tokio1-rustls-tls",
    "tracing",
] }
mrml = { version = "2.0.0-rc4", default-features = false, features = [
    "orderedmap",
    "parse",
    "render",
] }
scoped-futures = "0.1.3"
speedy-uuid = { path = "../../lib/speedy-uuid" }
thiserror = "1.0.50"
typed-builder = "0.18.0"

[lints]
workspace = true
