[package]
name = "kitsune-email"
edition.workspace = true
version.workspace = true

[package.metadata.cargo-machete]
ignored = ["askama_axum"] # See reason below.

[dependencies]
askama = "0.12.1"
askama_axum = "0.3.0" # Damn it, cargo. Because "kitsune" uses "askama" with the axum feature, we have to have the crate available here as well..
lettre = { version = "0.11.0", default-features = false, features = [
    "builder",
    "hostname",
    "pool",
    "smtp-transport",
    "tokio1",
    "tokio1-rustls-tls",
    "tracing",
] }
mrml = { version = "2.0.0-rc4", default-features = false, features = [
    "orderedmap",
    "parse",
    "render",
] }
thiserror = "1.0.49"
typed-builder = "0.17.0"
