[package]
name = "kitsune-url"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
smol_str = "0.2.1"
speedy-uuid = { path = "../../lib/speedy-uuid" }
typed-builder = "0.18.2"

[lints]
workspace = true
