[package]
name = "kitsune-observability"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.79"
http-body-util = "0.1.1"
http-compat = { path = "../../lib/http-compat" }
hyper = { version = "1.2.0", default-features = false }
kitsune-config = { path = "../kitsune-config" }
kitsune-http-client = { path = "../kitsune-http-client" }
metrics = "=0.22.0"
metrics-opentelemetry = { git = "https://github.com/aumetra/metrics-opentelemetry.git", rev = "95537b16370e595981e195be52f98ea5983a7a8e" }
metrics-tracing-context = "0.15.0"
metrics-util = "0.16.3"
miette = "7.2.0"
opentelemetry = { version = "0.22.0", default-features = false, features = [
    "trace",
] }
opentelemetry-http = "0.11.1"
opentelemetry-otlp = { version = "0.15.0", default-features = false, features = [
    "grpc-tonic",
    "http-proto",
    "metrics",
    "tls",
    "tls-roots",
    "trace",
] }
opentelemetry_sdk = { version = "0.22.1", default-features = false, features = [
    "rt-tokio",
] }
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-opentelemetry = { version = "0.23.0", default-features = false }
tracing-subscriber = "0.3.18"

[lints]
workspace = true
