[package]
name = "kitsune-observability"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1.74"
hyper = { version = "1.0.1", default-features = false }
kitsune-config = { path = "../kitsune-config" }
kitsune-http-client = { path = "../kitsune-http-client" }
metrics = "0.21.1"
metrics-opentelemetry = { git = "https://github.com/aumetra/metrics-opentelemetry.git", rev = "d4762c6704ecac8bca8f14ee201ce83d652c382a" }
metrics-tracing-context = "0.14.0"
metrics-util = "0.15.1"
miette = "5.10.0"
opentelemetry = { version = "0.21.0", default-features = false, features = [
    "trace",
] }
opentelemetry-http = "0.10.0"
opentelemetry-otlp = { version = "0.14.0", default-features = false, features = [
    "grpc-tonic",
    "http-proto",
    "metrics",
    "tls",
    "tls-roots",
    "trace",
] }
opentelemetry_sdk = { version = "0.21.1", default-features = false, features = [
    "rt-tokio",
] }
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-opentelemetry = { version = "0.22.0", default-features = false }
tracing-subscriber = "0.3.18"

[lints]
workspace = true
