[package]
name = "kitsune-federation"
edition.workspace = true
version.workspace = true

[dependencies]
kitsune-activitypub = { path = "../kitsune-activitypub" }
kitsune-cache = { path = "../kitsune-cache" }
kitsune-core = { path = "../kitsune-core" }
kitsune-db = { path = "../kitsune-db" }
kitsune-embed = { path = "../kitsune-embed" }
kitsune-federation-filter = { path = "../kitsune-federation-filter" }
kitsune-search = { path = "../kitsune-search" }
kitsune-service = { path = "../kitsune-service" }
kitsune-url = { path = "../kitsune-url" }
kitsune-webfinger = { path = "../kitsune-webfinger" }
typed-builder = "0.18.0"
