[package]
name = "kitsune-mastodon"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12.0"
diesel = "2.1.4"
diesel-async = "0.4.1"
futures-util = "0.3.29"
iso8601-timestamp = "0.2.12"
kitsune-cache = { path = "../kitsune-cache" }
kitsune-core = { path = "../kitsune-core" }
kitsune-db = { path = "../kitsune-db" }
kitsune-embed = { path = "../kitsune-embed" }
kitsune-service = { path = "../kitsune-service" }
kitsune-type = { path = "../kitsune-type" }
kitsune-util = { path = "../kitsune-util" }
mime = "0.3.17"
scoped-futures = "0.1.3"
serde = "1.0.193"
simd-json = "0.13.4"
smol_str = "0.2.0"
speedy-uuid = { path = "../../lib/speedy-uuid" }
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["rt"] }
tracing = "0.1.40"
typed-builder = "0.18.0"
