[package]
name = "kitsune-blocking"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
once_cell = "1.18.0"
rayon = "1.8.0"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["rt", "sync"] }
tracing = "0.1.40"
