[package]
name = "kitsune-language"
edition.workspace = true
version.workspace = true

[dependencies]
diesel = "2.1.4"
diesel-async = { version = "0.4.1", features = ["postgres"] }
isolang = { version = "2.3.0", features = [
    "english_names",
    "list_languages",
    "serde",
] }
rustc-hash = "1.1.0"
whatlang = { version = "0.16.3", optional = true }
whichlang = { version = "0.1.0", optional = true }

[features]
default = ["whatlang"]
