[package]
name = "phenomenon-http-signatures"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
http = "0.2.8"
ring = { version = "0.16.20", features = ["std"] }
thiserror = "1.0.37"

[features]
