[package]
name = "kitsune-messaging"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.64"
futures-util = "0.3.26"
redis = { version = "0.22.3", features = [
    "aio",
    "connection-manager",
    "tokio-comp",
] }
serde = "1.0.152"
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros", "rt", "sync"] }
tokio-stream = { version = "0.1.12", features = ["sync"] }
tracing = "0.1.37"
