[package]
name = "kitsune-type"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
time = { version = "0.3.20", features = ["serde"] }
utoipa = { version = "3.3.0", features = ["chrono", "uuid"] }
uuid = { version = "1.3.1", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
