[package]
name = "kitsune-type"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
smol_str = "0.2.0"
time = { version = "0.3.22", features = ["formatting", "parsing", "serde"] }
utoipa = { version = "3.3.0", features = ["chrono", "uuid"] }
uuid = { version = "1.3.4", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
