[package]
name = "kitsune-search-proto"
version.workspace = true
edition = "2021"

[dependencies]
prost = "0.11.9"
serde = { version = "1.0.166", features = ["derive"] }
tonic = { version = "0.9.2", default-features = false, features = [
    "codegen",
    "transport",
    "prost",
] }

[build-dependencies]
protoc-bin-vendored = { version = "3.0.0", optional = true }
tonic-build = "0.9.2"

[features]
default = []
vendored-protoc = ["protoc-bin-vendored"]
